prefixes:
  - "!"

core:
  area:
    start:
      x: 0
      y: 0
      z: 0
    end:
      x: 15
      y: 0
      z: 15
  coreName: "[{text:\"Nitori\",color:\"blue\"},{text:\"Bot \",color:\"green\"},{text:\"Core\"}]"

colors:
  integer: "gold"
  commands:
    primary: "blue"
    secondary: "dark_aqua"
    tertiary: "aqua"
  help:
    Public: "blue"
    trusted: "dark_aqua"
    admin: "aqua"
    owner: "light_purple"
    console: "dark_purple"

console:
  prefix: "c."

bots:
  - host: "localhost"
    port: 25565
    serverName: "localhost"
    username: "NitoriBotJava"
    reconnectDelay: 6000
    selfcareInterval: 1000