prefixes = ["!"]

[debug]
host = "http://localhost:8080"

[console]
prefix = "c."
timezone = "America/CHICAGO"


[[bots]]
host = "localhost"
version = "1.21.8"
username = "meow"
serverName = "localhost"
hideErrors = true
scInterval = 1000
